package com.example.currencyconverter.common

object Constant {

    const val BASE_URL = "https://cdn.jsdelivr.net/npm/@fawazahmed0/"
}

enum class CurrencyCodes(val fullName: String) {
    AED("United Arab Emirates Dirham"),
    ARS("Argentine Peso"),
    AUD("Australian Dollar"),
    BDT("Bangladeshi Taka"),
    BGN("Bulgarian Lev"),
    BHD("Bahraini Dinar"),
    BRL("Brazilian Real"),
    CAD("Canadian Dollar"),
    CHF("Swiss Franc"),
    CLP("Chilean Peso"),
    CNY("Chinese Yuan"),
    COP("Colombian Peso"),
    CZK("Czech Koruna"),
    DKK("Danish Krone"),
    EGP("Egyptian Pound"),
    EUR("Euro"),
    GHS("Ghanaian Cedi"),
    GBP("British Pound Sterling"),
    HKD("Hong Kong Dollar"),
    HUF("Hungarian Forint"),
    IDR("Indonesian Rupiah"),
    ILS("Israeli Shekel"),
    INR("Indian Rupee"),
    JMD("Jamaican Dollar"),
    JPY("Japanese Yen"),
    KES("Kenyan Shilling"),
    KRW("South Korean Won"),
    KWD("Kuwaiti Dinar"),
    LKR("Sri Lankan Rupee"),
    MAD("Moroccan Dirham"),
    MXN("Mexican Peso"),
    MYR("Malaysian Ringgit"),
    NGN("Nigerian Naira"),
    NOK("Norwegian Krone"),
    NZD("New Zealand Dollar"),
    OMR("Omani Rial"),
    PHP("Philippine Peso"),
    PKR("Pakistani Rupee"),
    PLN("Polish Zloty"),
    QAR("Qatari Riyal"),
    RON("Romanian Leu"),
    RUB("Russian Ruble"),
    SAR("Saudi Riyal"),
    SEK("Swedish Krona"),
    SGD("Singapore Dollar"),
    THB("Thai Baht"),
    TRY("Turkish Lira"),
    TWD("New Taiwan Dollar"),
    USD("United States Dollar"),
    VND("Vietnamese Dong"),
    ZAR("South African Rand");
}